### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by ovol59** [HKJL10201/fast-feature-fool#1]
Unable to download "https://www.dropbox.com/s/k4tamvdjndyvgws/preprocessed_images_224.npy?raw=1".

**Comment by HKJL10201** [comment]
This link seems to have expired.

**Comment by ovol59** [comment]
How should I make this file?
What is the difference between 227 and 224?
Thanks.

**Comment by HKJL10201** [comment]
Sorry, I am not the original author. I cloned this repo for research purpose two years ago. 
The link of the original work is [https://github.com/val-iisc/fast-feature-fool](https://github.com/val-iisc/fast-feature-fool)
You can ask the original authors. I hope it will help you.
